[[themes]]
name = "gruvbox"
[themes.palette]
background = "#282828"
foreground = "#ebdbb2"
black = "#282828"
red = "#cc241d"
green = "#98971a"
yellow = "#d79921"
blue = "#458588"
magenta = "#b16286"
cyan = "#689d6a"
white = "#a89984"
bright_black = "#928374"
bright_red = "#fb4934"
bright_green = "#b8bb26"
bright_yellow = "#fabd2f"
bright_blue = "#83a598"
bright_magenta = "#d3869b"
bright_cyan = "#8ec07c"
bright_white = "#ebdbb2"
[themes.component_style]
like = { fg = "Red", modifiers = ["Bold"] }
playback_progress_bar = { fg = "Green", bg = "Black" }
table_header = { fg = "Yellow", modifiers = ["Bold"] }

[[themes]]
name = "everforest"
[themes.palette]
background = "#2d353b"
foreground = "#d3c6aa"
black = "#2d353b"
red = "#e67e80"
green = "#a7c080"
yellow = "#e69875"
blue = "#7fbbb3"
magenta = "#d699b6"
cyan = "#83c092"
white = "#d3c6aa"
bright_black = "#2d353b"
bright_red = "#e67e80"
bright_green = "#a7c080"
bright_yellow = "#dbbc7f"
bright_blue = "#7fbbb3"
bright_magenta = "#d3869b"
bright_cyan = "#83c092"
bright_white = "#d3c6aa"
[themes.component_style]
playback_metadata = { fg = "White" }
playlist_desc = { fg = "White", modifiers = ["Dim"] }
table_header = { fg = "Yellow" }
like = { fg = "Red", modifiers = ["Bold"] }
